set_property SRC_FILE_INFO {cfile:{/home/mk/Documents/fpga projects/project_2/project_2.srcs/constrs_1/new/swled_constraint.xdc} rfile:../../../project_2.srcs/constrs_1/new/swled_constraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports SW]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports LED]
