set_property DRIVE 12 [get_ports LED]
set_property IOSTANDARD LVCMOS33 [get_ports SW]
set_property IOSTANDARD LVCMOS33 [get_ports LED]
set_property PACKAGE_PIN V17 [get_ports SW]
set_property PACKAGE_PIN L1 [get_ports LED]
